runtime: nodejs20
env: standard

handlers:
  - url: /(.*\..+)$
    static_files: dist/\1
    upload: dist/(.*\..+)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

default_expiration: "1h"
